#!/bin/bash

# Count total number of words in the file.
echo "There are $(cat $1 | wc -l) words in $1"

# Count the number of words between 2-7 characters long.
echo "There are $(cat $1 | grep -P '^[a-zA-Z]{2,7}$' | wc -l) words between 2 and 7 characters long"
